name: build-and-publish-pypi

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        id: checkout
        uses: actions/checkout@v4
      -
        name: setup-python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      -
        name: free-up-space
        run: |
          echo "Disk usage before cleanup:"
          df -h
          sudo rm -rf /opt/hostedtoolcache /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm
          echo "Disk usage after cleanup:"
          df -h
      -
        name: install-packages
        id: install-packages
        run: |
          python -m pip install --upgrade pip setuptools wheel build
      -
        name: build-package
        id: build-package
        run: |
          python -m build
      -
        name: check-for-dist-preupload
        run: |
          echo "Checking dist/ after build..."
          ls -lah dist/
      -
        name: upload-package
        id: upload-package
        uses: actions/upload-artifact@v4
        with:
          name: python-dist  # Explicit artifact name
          path: dist/
  publish-package:
    needs:
      - build-package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/psifx
    permissions:
      id-token: write
    steps:
      -
        name: free-up-space
        run: |
          echo "Disk usage before cleanup:"
          df -h
          sudo rm -rf /opt/hostedtoolcache /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm
          echo "Disk usage after cleanup:"
          df -h
      -
        name: download-package
        id: download-package
        uses: actions/download-artifact@v4
        with:
          name: python-dist  # matches name at upload
          path: dist/
      -
        name: check-for-dist-postupload
        run: |
          echo "Checking dist/ after downloading artifact..."
          ls -lah dist/
      -
        name: publish-pypi
        id: publish-pypi
        uses: pypa/gh-action-pypi-publish@release/v1
