name: run-tests

on:
  push:
    branches:
      - main
    paths:
      - 'psifx/**'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - 'psifx/**'


jobs:
  run-tests:
    name: Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]

    steps:
      - uses: actions/checkout@v3

      - name: Free up space
        run: |
          df -h
          sudo rm -rf /opt/hostedtoolcache /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm
          df -h

      - name: Build Docker image
        run: |
          docker build \
            --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
            -t psifx-test:${{ matrix.python-version }} .

      - name: Start container
        run: |
          docker run -dit --name test-container \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
            psifx-test:${{ matrix.python-version }}

      - name: Install requirements
        run: |
          docker exec test-container pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          docker exec test-container pytest -rs tests

      - name: Stop and remove container
        if: always()
        run: |
          docker rm -f test-container
